# Site setting
title: 想的
github_username: 'g4407143@gmail.com'
email: '491323894@qq.com'
footer_description: '不会翻译思想的作家，不是个好读者 （雾）'

markdown: kramdown
sass:
  sass_dir: assets/sass
  style: compressed